project_params:
  dataset_path: /home/g/workspace/dataset #数据集文件夹
  result_path: /home/g/workspace/common_project/result #工程结果文件夹

algorithm_params:
  cloud_filter_params: #点云滤波参数
    method: "voxel"
  cloud_register_params: #点云配准参数
    method: "gicp"
  optimizer_params: #优化器参数
    method: "g2o"

topic_name:
  imu_topic: /alphasense_driver_ros/imu
  lidar_topic: /hesai/pandar
  raw_gnss_topic: /ublox_driver/range_meas
  solved_gnss_topic: /ublox_driver/receiver_lla

lidar_params: #激光雷达参数
  T_body_lidar:
    t: 0.479112, 0.052000, -0.019785 #xyz
    q: 0.001234, 0.001234, 0.707106, 0.707106 #xyzw

gnss_params: #GNSS参数
  T_body_gnss:
    t: 0.0, 0.0, 0.0 #xyz
    q: 0.0, 0.0, 0.0, 1.0 #xyzw

imu_params:
  accel_noise_std: 0.0014929303436999736
  accel_bias_noise_std: 6.883010680707546e-05
  gyro_nose_std: 0.00029824119649206544
  gyro_bias_noise_std: 1.2013119882828282e-06
  T_body_imu:
    t: 0.516857, 0.043450, -0.092900 #xyz
    q: 0.999998, 0.000000, -0.001745, 0.000000 #xyzw

