# @brief    backend YAML
# @date    2024-04-09 update
# @version 0.1.1

#topic subscriber------------------------------------------------
topic_sub: #
  cloud_sub_topic: /synced_no_ground_cloud #sensor_msgs/PointCloud2
  gnss_sub_topic: /synced_gnss_odom
  lidar_odom_sub_topic: /lidar_odom

#pose graph setting-------------------------------------------------
pose_graph:
  keyframe_distance: 2.0

  lidar_odom_noise: [0.5, 0.5, 0.5, 0.001, 0.001, 0.001] #xyzrpy
  gnss_odom_noise: [2.0, 2.0, 2.0] #xyz
  imu_odom_noise: [0.5, 0.5, 0.5, 0.001, 0.001, 0.001] #xyzrpy

  new_gnss_cnt_max: 0
  new_loop_cnt_max: 0
  new_key_frame_cnt_max: 10

  result_folfer: ""

  extrinsic:
    lidar_to_body:
    [
      0.999998,-0.000785403,0.00202441,0.810544,
      0.000755307, 0.99989,0.0148245,-0.307054,
      -0.00203583,-0.014823,0.999888,0.802724,
      0.0,0.0,0.0,1.0,
    ]
    imu_to_body:
    [
      1.0,0.0,0.0,0.0, 
      0.0,1.0,0.0,0.0, 
      0.0,0.0,1.0,0.0, 
      0.0,0.0,0.0,1.0, 
    ]
    cam_to_lidar:
    [
      7.967514e-03, -9.999679e-01, -8.462264e-04 ,-1.377769e-02,
      -2.771053e-03, 8.241710e-04 ,-9.999958e-01 ,-5.542117e-02,
      9.999644e-01 ,7.969825e-03 ,-2.764397e-03,-2.918589e-01,
      0.0,0.0,0.0,1.0,
    ]



